/**
 * 모델 학습 클래스 순서에 기반한 카테고리 목록입니다.
 */
export const CATEGORIES = [
  { id: "dinosaur", label: "공룡" },
  { id: "elephant", label: "코끼리" },
  { id: "rocket", label: "로켓" },
  { id: "guitar", label: "기타" },
  { id: "umbrella", label: "우산" },
  { id: "butterfly", label: "나비" },
  { id: "bicycle", label: "자전거" },
  { id: "heart", label: "하트" },
  { id: "star", label: "별" },
  { id: "tree", label: "나무" },
  { id: "car", label: "자동차" },
  { id: "house", label: "집" },
  { id: "apple", label: "사과" },
  { id: "book", label: "책" },
  { id: "chair", label: "의자" },
  { id: "cup", label: "컵" },
  { id: "diamond", label: "다이아몬드" },
  { id: "fish", label: "물고기" },
  { id: "flower", label: "꽃" },
  { id: "hat", label: "모자" },
  { id: "key", label: "열쇠" },
  { id: "leaf", label: "나뭇잎" },
  { id: "moon", label: "달" },
  { id: "mountain", label: "산" },
  { id: "pencil", label: "연필" },
  { id: "phone", label: "전화기" },
  { id: "ship", label: "배" },
  { id: "sun", label: "태양" },
  { id: "watch", label: "시계" },
  { id: "cloud", label: "구름" },
];
